import React from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import { useSpring, animated } from "react-spring";
import Loader from "../Components/Loader";
export default function LandingPage() {
  const [isLoaded, setIsLoaded] = useState(false);
  const [personaLoading, setPersonaLoading] = useState(false);

  useEffect(() => {
    setIsLoaded(true);
  }, []);

  const fadeIn = useSpring({
    opacity: isLoaded ? 1 : 0,
    transform: isLoaded ? "translateY(0)" : "translateY(-20px)",
    config: { duration: 500 }, // Adjust the duration
  });
  const navigate = useNavigate();
  const handleGenerateClick = async () => {
    try {
      setPersonaLoading(true);
      const response = await axios.get(
        "https://persona-backend-e9uc.onrender.com/generate-persona"
      );
      // Handle the response data here
      // console.log(response.data);
      // Storing the object in localStorage
      localStorage.setItem("persona", JSON.stringify(response.data));

      // Retrieving the object from localStorage
      setPersonaLoading(false);
      //console.log(persona);
      navigate("/persona");
    } catch (error) {
      // Handle the error here
      console.error(error);
    }
  };

  return (
    <animated.div
      className="font-montesserat absolute w-full min-h-full bg-teal-400 flex  items-center justify-center p-2"
      style={fadeIn}
    >
      <div className="w-3/4 flex flex-col space-y-[20px] items-center">
        <h className="text-5xl font-extrabold text-teal-800 ">
          PersonaAI<span className="text-yellow-300">.</span>
        </h>
        <p className="hidden lg:block text-xl text-teal-100 font-thin text-center">
          The{" "}
          <span className="font-bold text-teal-600">Persona.AI project</span>{" "}
          leverages the remarkable capabilities of OpenAI's GPT-3 API (DALL·E)
          to craft spontaneous personas, complete with biodata and an
          AI-generated image. Demonstrating the vast potential of{" "}
          <span className="font-bold text-teal-600">OpenAI's API</span>, the
          biodata, encompassing details like name, age, occupation, and
          location, is intelligently generated by the{" "}
          <span className="font-bold text-teal-600">GPT-3 language model</span>.
          Complementing this, the AI-generated image, powered by the{" "}
          <span className="font-bold text-teal-600">DALL·E API</span>, visually
          represents the persona based on textual descriptions. The project,
          seamlessly implemented through the{" "}
          <span className="font-bold text-teal-600">Flask web framework</span>,
          functions as a web application, requiring users to possess an{" "}
          <span className="font-bold text-teal-600">OpenAI API key</span>
          and install essential packages such as Flask and Requests. In essence,
          the{" "}
          <span className="font-bold text-teal-600">
            {" "}
            Persona Generator
          </span>{" "}
          stands as an engaging testament to the prowess of{" "}
          <span className="font-bold text-teal-600">OpenAI's API</span>,
          showcasing its ability to generate diverse and personalized content
          with a touch of creativity and fun.
        </p>
        <p className="block lg:hidden text-sm text-teal-100 font-thin text-center">
          <span className="font-bold text-teal-600">Persona.AI project</span>{" "}
          uses OpenAI's GPT-3 API (DALL·E) to create personas with biodata and
          an AI-generated image. The biodata includes details like name, age,
          occupation, and location, intelligently generated by the{" "}
          <span className="font-bold text-teal-600">GPT-3 language model</span>.
          The AI-generated image, powered by{" "}
          <span className="font-bold text-teal-600">DALL·E API</span>, visually
          represents the persona. The{" "}
          <span className="font-bold text-teal-600">Flask web framework</span>{" "}
          powers the web application, requiring users to possess an{" "}
          <span className="font-bold text-teal-600">OpenAI API key</span> and
          install essential packages. The{" "}
          <span className="font-bold text-teal-600">Persona Generator</span>{" "}
          showcases the prowess of{" "}
          <span className="font-bold text-teal-600">OpenAI's API</span>,
          generating diverse and personalized content with creativity and fun.
        </p>

        <button
          className={`${
            personaLoading ? "" : "bg-teal-500 hover:bg-teal-600"
          } font-bold text-teal-200  rounded-md p-[10px]`}
          onClick={handleGenerateClick}
        >
          {personaLoading ? <Loader /> : "Generate Persona"}
        </button>
      </div>
    </animated.div>
  );
}
